### ISSUE TITLE
Missing summary chart isn't visible

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#118]
<img width="1411" alt="Screenshot 2019-06-17 at 12 30 48" src="https://user-images.githubusercontent.com/406916/59598127-c2266d00-90fb-11e9-83b0-5864156cdfaa.png">

The content of the chart is invisible.

**Comment by dpordomingo** [comment]
If I understood how the dashboards are built, I'd say that this problem is not caused by the new typography but because of a too narrow chart.

imo we should edit our current dashboard to leave enough space to that chart, as done by the PR #129

In the following screenshot, you can see an example of this problem with our **current chart**, and our **current `master`** that shows.
In summary, the dashboard layout (not the css) affects and impacts the data displayed inside.

![image](https://user-images.githubusercontent.com/2437584/59853640-944a5e00-9371-11e9-8233-9f919709124c.png)

**Comment by ricardobaeta** [comment]
Please have [this comment](https://github.com/src-d/sourced-ui/issues/114#issuecomment-504059980) in mind.
