### ISSUE TITLE
Most active repos chart isn't sorted by value

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#140]
<img width="1460" alt="Screenshot 2019-06-20 at 12 33 55" src="https://user-images.githubusercontent.com/406916/59842894-bfc04f00-9357-11e9-9956-4eddc26b5d53.png">

**Comment by gomesfernanda** [comment]
According to my empirical investigation, for some reason, the sorting on the bar chart is done according to the first metric given on the settings (instead of the total count merged + open + closed, as desired). In this case, It's sorting by `Merged` metric.

<img width="1392" alt="most_active_001" src="https://user-images.githubusercontent.com/21245928/59980855-bf32ed00-95d1-11e9-9e81-627c2dbafb39.png">

Checking what happens if we change the order of the metrics, we notice that it will sort according to the first given metric.

<img width="1390" alt="most_active_002" src="https://user-images.githubusercontent.com/21245928/59980858-bfcb8380-95d1-11e9-948c-aef097ef1b9b.png">

<img width="1393" alt="most_active_003" src="https://user-images.githubusercontent.com/21245928/59980856-bfcb8380-95d1-11e9-9744-e5ae9b389f59.png">


The query we have is:
```sql
SELECT CONCAT(repository_owner, '/', repository_name) AS repository,
DATE(created_at) as date_created,
date(merged_at) as date_merged,
date(closed_at) as date_closed
FROM pull_requests
```
And the result is a table with columns: repo, date created, date merged, date closed.

I have no answer on how to fix this without being able to choose how to sort the bar chart or how to change the query so I could select only records from the last 30 days (we currently filter this on the Superset UI).

**Comment by marnovo** [comment]
@gomesfernanda maybe in the query itself we can add one line that adds up all created/merged/closed and sort by that but not display it (sorting could be in the query itself or in the UI, whatever works w/o showing it).

**Comment by gomesfernanda** [comment]
What I did for now (locally) is modify the query to get the last 30 days on it:

```sql
SELECT CONCAT(repository_owner, '/', repository_name) AS repository,
COUNT(created_at) AS count_created,
COUNT(merged_at) AS count_merged,
(COUNT(closed_at) - COUNT(merged_at)) AS count_closed,
(COUNT(*) - count(closed_at)) AS count_open
FROM pull_requests
WHERE DATE(created_at) >= DATE(now()) - INTEGER '30'
GROUP BY repository
ORDER BY count_created DESC
```

And have the first metric as "Created issues". This way, created repos is the sum of closed, open and merged, and the chart is sorted descending by value.

<img width="1390" alt="most_active_repos" src="https://user-images.githubusercontent.com/21245928/60040187-c8ce5a80-968e-11e9-9087-dfd2e033cd2f.png">

**Comment by smacker** [comment]
After another thought sorting by "created" doesn't solve the issue. It absolutely possible to have more merged/closed issues than created in 1 month period.

**Comment by gomesfernanda** [comment]
So we have to think of another alternative.

I was navigating through the demo instance and I found this chart that is sorted correctly. We should try to replicate it for the most active repos.

![image](https://user-images.githubusercontent.com/21245928/60359610-e01f8780-99af-11e9-89f4-c4e0aa2c140f.png)
