### ISSUE TITLE
Breakdown chart is broken

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#192]
<img width="702" alt="Screenshot 2019-07-03 at 16 31 11" src="https://user-images.githubusercontent.com/406916/60600201-08dcbe00-9db0-11e9-9fe7-903fa2cf155b.png">

<img width="701" alt="Screenshot 2019-07-03 at 16 32 50" src="https://user-images.githubusercontent.com/406916/60600326-37f32f80-9db0-11e9-8c77-335765ffffec.png">

Most probably because of the Typography PR.

**Comment by dpordomingo** [comment]
This is already happening with our first release of `sourced-ui:v0.1.0`,
so I assume it's a problem with the original chart source-code.
![image](https://user-images.githubusercontent.com/2437584/60656432-b3f08480-9e4f-11e9-97ae-f9c4521101b1.png)

**Comment by smacker** [comment]
it became worse. Before the text was in the wrong place but at least readable. Now (when it's white) it is not.

**Comment by dpordomingo** [comment]
This is also `sourced-ui:v0.1.0`,

![image](https://user-images.githubusercontent.com/2437584/60657353-81478b80-9e51-11e9-991e-a08d611893ee.png)

What we can see, is that the problem goes wrong or better depending on the:
- chart size,
- the text length.

So yes, since changing the font size affect the text length, it's not the origin of the problem.

Example:
This chart is "ok"
![image](https://user-images.githubusercontent.com/2437584/60657551-d5527000-9e51-11e9-95a3-073437a1ec4a.png)

If you change its size, the labels explode
![image](https://user-images.githubusercontent.com/2437584/60657686-0763d200-9e52-11e9-86ae-a793cdc56bb2.png)

**Comment by ricardobaeta** [comment]
Hi @smacker ! This issue is now fixed as you can see 👇 . It will be included on the typography-fixes PR. Once it's merged we close this. I only have two comments about this:

1) The text positioning was solved with css
2) For us to have the text proper positioned if its length is large, as you can see on the screenshots, the width of the chart itself on the dashboard needs to be increased.

**Dashboard**
![image](https://user-images.githubusercontent.com/1746146/60661442-d2f01600-9e51-11e9-87d6-e500b9afd646.png)

![image](https://user-images.githubusercontent.com/1746146/60661412-c1a70980-9e51-11e9-8075-4c315144297e.png)

![image](https://user-images.githubusercontent.com/1746146/60661344-a5a36800-9e51-11e9-870b-fdf3a3f437b7.png)

**Edit Chart**
![image](https://user-images.githubusercontent.com/1746146/60661583-1b0f3880-9e52-11e9-8656-921a7f95b1fa.png)

**Comment by carlosms** [comment]
Fixed in #196
