### ISSUE TITLE
Update superset changes from latest upstream release

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#250]

**Comment by smacker** [comment]
Merging upstream isn't straight forward because upstream releases have cherry-picked commits, so the history isn't linear.

Instruction for merge written a while ago: https://gist.github.com/smacker/b8a6ccf5539ad2a209c97fe878233ac7

Superset internals were refactored in the new release so for cancelation feature it would be easy to revert current changes and apply patch from here: https://github.com/apache/incubator-superset/pull/7611

**Comment by smacker** [comment]
Another pain point is a migration that exists only in our fork. It would break the order of migrations in upstream and `db upgrade` would fail. Most probably the best solution is to introduce yet another migration that would merge our current head with what has changed in upstream. See 5c76216bec29d4ba5c9754397ba62b0bd45695e3 as example.
